export const ADD_SHIRT = "ADD_SHIRT";
export const REMOVE_SHIRT = "REMOVE_SHIRT";
export const SET_CARDS = "SET_CARDS";
export const FETCH_CARDS_FAILED = "FETCH_CARDS_FAILED";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_SUCCESS";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const INIT_SINGLE_PAGE = "INIT_SINGLE_PAGE";
export const FETCH_SINGLE_PAGE_SUCCESS = "FETCH_SINGLE_PAGE_SUCCESS";
export const FETCH_SINGLE_PAGE_FAILED = "FETCH_SINGLE_PAGE_FAILED";
export const PURCHASE_SHIRT_START = "PURCHASE_SHIRT_START";
export const PURCHASE_SHIRT_SUCCESS = "PURCASE_SHIRT_SUCCESS";
export const PURCHASE_SHIRT_FAILED = "PURCASE_SHIRT_FAILED";
export const OPEN_MODAL = "OPEN_MODAL";
